---
language: go

before_install:
  - go get github.com/mattn/goveralls
  
jobs:
  include:
    - stage: Linting
      script: go fmt -v ./... && go vet -v ./...
    - go: 1.7.x
      script: "go test -cover -v ./..."
    - go: 1.8.x
      script: "go test -cover -v ./..."
    - go: 1.9.x
      script: "$GOPATH/bin/goveralls -service=travis-ci"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
