---
language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  
jobs:
  fast_finish: true
  allow_failures:
    - stage: Linting
    - go: tip
  include:
    - stage: Linting
      script: go vet -v ./...
    - stage: Linting
      script: golint $(go list ./... | fgrep -v '/vendor/')
    - stage: Test
      go: 1.7.x
    - stage: Test
      go: 1.8.x
    - stage: Test
      go: 1.9.x
    - stage: Test
      go: tip
      script: "$GOPATH/bin/goveralls -service=travis-ci"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

script: "go test -cover -v ./..."
